# Generated by Django 4.1.7 on 2023-04-24 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='transaction_performed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
