# Generated by Django 4.2 on 2023-04-20 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinmate',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
