# Generated by Django 4.2 on 2023-04-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmatesheet',
            name='account_number',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='jims_app.accounts'),
        ),
    ]
