# Generated by Django 4.1.7 on 2023-03-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0002_login_delete_inmate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='pass_word',
            new_name='password',
        ),
    ]
