# Generated by Django 4.2 on 2023-04-15 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0004_person_delete_login_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('inmate_id', models.CharField(max_length=200)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=2)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jims_app.accounts')),
            ],
        ),
    ]
