# Generated by Django 4.2 on 2023-04-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0004_person_delete_login_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200)),
                ('inmate_id', models.CharField(max_length=200)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
