# Generated by Django 4.2 on 2023-04-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0005_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transaction_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(max_length=2)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
