# Generated by Django 4.2 on 2023-04-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0006_transactiondetails_remove_accounts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_id',
            field=models.CharField(auto_created=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
