# Generated by Django 4.2 on 2023-04-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jims_app', '0007_alter_transactiondetails_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
